#version: '2'
#
#services:
#  sd-editor:
#    image: ghcr.io/knaw-huc/service-huc-editor:2.0-RC9
#    environment:
#      - BASE_URL=http://localhost:1210
#      - CDN_URL=https://alpha-cmdicdn.sd.di.huc.knaw.nl
#    volumes:
#      - ./data:/home/huc/huc-editor-service/data
#    networks:
#      - sd-editor
#    ports:
#      - '1210:1210'
#
#networks:
#  sd-editor:
#    external: false
#
services:
  sd-editor:
    #image: ghcr.io/knaw-huc/service-huc-editor:2.0-rc11
    image: registry.diginfra.net/tsd/huc-editor-services:2.0-RC12-alpha2
    environment:
      - BASE_URL=http://localhost:1210
      - CDN_URL=http://localhost:1310/
    volumes:
      - ./data:/home/huc/huc-editor-service/data
    networks:
      - sd-editor
    ports:
      - '1210:1210'
  sd-editor-cdn:
    image: registry.diginfra.net/tsd/huc-generic-editor:1.3-RC9-alpha2
    restart: unless-stopped
    ports:
      - 1310:80
    networks:
      - sd-editor

networks:
  sd-editor:
    external: false
